package com.ecommerce.paymentservice.dto;

import lombok.Getter;
import lombok.Setter;

import java.util.Map;
import java.util.UUID;

@Getter
@Setter
public class PaymentResponse {
    private UUID paymentId; // A unique ID generated by the payment gateway by us
    private Long orderId;
    private String paymentGatewayId; // e.g., "STRIPE", "RAZORPAY"
    private String paymentGateway; // e.g., "STRIPE", "RAZORPAY"
    private String checkoutUrl; // URL to redirect the user to (for hosted payment pages)
    private String sessionId; // For gateways like Stripe that provide a session ID
    private String status; // e.g., "PENDING", "CREATED"
    private Map<String, Object> additionalInfo; // Any other info
}
